### ISSUE TITLE
Develop The 3 Ready Interfaces (Sign in, Homepage, Report Incident - Call)

### ISSUE THREAD

**Issue by JenniferOgbang** [JenniferOgbang/Gender-Based-Violence-Support-web-app-project#1]
Kindly develop the interfaces the 3 pages (Sign in, Homepage, Report Incident - Call) based on the design uploaded. 
You can find the design specifications, measurements, and assets in Zeplin: https://zpl.io/Prqy6oM

**Comment by git-ellea** [comment]
Done, added 3 pages to the site
